### ISSUE TITLE
Design metadata upload API in swaggerhub

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#2]
Need to define api endpoints that will be used in the metadata upload workflow https://osf.io/v7f9t/wiki/Metadata%20Entry%20Workflow/

The idea is that you will have an endpoint for each of the add_<tablename>* functions in https://github.com/az-digitalag/betydbtools/pull/2/files 

But probably easiest to follow the sql here https://osf.io/v7f9t/wiki/Metadata%20Entry%20Workflow/

Completion criteria
* [x] published on swaggerhub
* [x] add a *.yaml file in openapi 3.0 schema to the repository

**Comment by saurabh1969** [comment]
I prepared the first draft of documentation as per #2.

 You can see the SwaggerUI [here.](https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/0.0.1)

**Comment by saurabh1969** [comment]
See pull request #3 .
