### ISSUE TITLE
Extra assignment statement causes issues

### ISSUE THREAD

**Issue by Chris-Schnaufer** [PecanProject/BETYdb-YABA#26]
The following line should be removed since `data` variable already has the notes: https://github.com/PecanProject/BETYdb-YABA/blob/14625fb17168af3ce004fb8d2616f6aef691ca7b/app/Meta.py#L154

Causes a crash due to `data_g` probably not having notes field.

**Comment by saurabh1969** [comment]
Implemented in #28
