### ISSUE TITLE
Move array initialization to inside of loop

### ISSUE THREAD

**Issue by Chris-Schnaufer** [PecanProject/BETYdb-YABA#27]
The array needs to be initialized inside the loop at the following location: https://github.com/PecanProject/BETYdb-YABA/blob/14625fb17168af3ce004fb8d2616f6aef691ca7b/app/Meta.py#L145

Right now, it accumulates every point from each geometry object and doesn't start fresh for each object.

**Comment by saurabh1969** [comment]
That was a blunder from side.Corrected in #28
