### ISSUE TITLE
Create an interface to 'add new experiments' 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#36]
This should provide a GUI front end to the python client. https://github.com/PecanProject/BETYdb-YABA/blob/master/client/client.py#L27 

It should accept the fields:

* Experiment Name
* Start Date
* End Date
* Description
* Design

And should be inserted into the experiments table in BETYdb using the API client

**Comment by shivanshu1086** [comment]
Yes @dlebauer , we can do it with **tkinter** a python library for GUI. 
Can I try to work on that?

**Comment by yuvrajdalia** [comment]
hey @dlebauer, I have just created a pull request addressing this issue. Please have a look at it and tell me if some other changes are required.

**Comment by dlebauer** [comment]
Thanks @yuvrajdalia - with the new spreadsheet based approach in this will not be required
