### ISSUE TITLE
NameError: name 'Response' is not defined under home method in BETYdb-YABA/app/server.py

### ISSUE THREAD

**Issue by smdp2000** [PecanProject/BETYdb-YABA#38]
https://github.com/PecanProject/BETYdb-YABA/blob/64b540ef21838d5b47469896b95672bb4ac00f48/app/server.py#L28

**Comment by smdp2000** [comment]
@dlebauer I have found a fix for this , I want to work on this.

**Comment by dlebauer** [comment]
Hi @smdp2000 - thanks for reporting this bug and providing a solution in #39 ! Could you provide a little bit more detail on what you did that caused the bug to occur - the specific command required to reproduce the error, as well as what you expected to occur? Sorry it appears that this repository doesn't have a bug reporting template, but the basic ingredients are 1) minimal reproducible example code, 2) what you expected to happen, and 3) what happened instead - plus any ideas on how to fix the error (which you provided, thanks!).

**Comment by dlebauer** [comment]
Not reproducible - closing
