### ISSUE TITLE
Implementing MetaData upload API

### ISSUE THREAD

**Issue by saurabh1969** [PecanProject/BETYdb-YABA#4]
- Implementation of metadata upload api with respect to: [https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.1](https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.1)

- SQL Query as per : [https://osf.io/v7f9t/wiki/Metadata%20Entry%20Workflow/](https://osf.io/v7f9t/wiki/Metadata%20Entry%20Workflow/)

- Upload will be done to the following tables:
1.Experiment
2.Sites
3.Treatments
4.cultivars
5.citations
6.experiments_sites
7.experiments_treatments
8.sites_cultivars
9.citations_sites

Completion criteria:
&#9744;  Setup Flask
&#9744;  Creating endpoints for each table
&#9744; Pull Request

**Comment by KristinaRiemer** [comment]
@saurabh1969 the link to Swaggerhub is broken.

**Comment by saurabh1969** [comment]
@KristinaRiemer try this one:[https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.1](https://app.swaggerhub.com/apis-docs/y51/bet-ydb_yaba/1.0.1)

**Comment by KristinaRiemer** [comment]
As the API has been implement and works when `PGHOST` is set manually, closing this in favor of the more specific #8.
