### ISSUE TITLE
Create a validation/review page for users to validate data before upload

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#41]
A proposed validation / review page. The goal of this is to make sure that the person uploading the metadata has a chance to confirm that the metadata they are uploading is correct / consistent with how they think it should be It can look like this:

![image](https://user-images.githubusercontent.com/464871/81606718-69ea0080-9388-11ea-9e74-ea1c40ceaf35.png)

Overview - 

* Use [psql transactions](https://www.postgresql.org/docs/8.3/tutorial-transactions.html) to validate data with the backend (start session w/ begin and end with commit or rollback)
* the position of each rectangle is defined by the geometry field in the shapefile - these will go into the sites.geometry field
   * for the first plot you can get the cultivars for each plot through a many-to-many join with sites thus: `select name as cultivar, sitename as plot from cultivars join sites_cultivars on cultivars.id = sites_cultivars.cultivar_id join sites on sites_cultivars.site_id = sites.id`
   * for the next two plots you can find experiments for each site through the experiments_sites table, and treatments through the experiments_treatments table
* Use [Leaflet](https://leafletjs.com/) to visualize 
   * you can use [shapefile extension](https://github.com/calvinmetcalf/leaflet.shapefile) 
   * later it might be better to convert shapefile to geojson that leaflet handles natively.

Bonus: (can create a new issue for this): a page overlaying plots on a satellite or drone imagery to confirm the correct positions in space.

**Comment by KristinaRiemer** [comment]
Rough version of joins: treatments as t join et on t.id = et.treatment_id join experiments as e on et.experiment_id = e.id join es on es.site_id = sites.id

**Comment by im-prakher** [comment]
Done in 

- [interface/src/components/data-visual.js](https://github.com/PecanProject/BETYdb-YABA/blob/ee818a85aca3a91bf506a671bb8ed8d4e1a64191/interface/src/components/data-visual.js)
- [interface/src/components/stylesheets/visual.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/visual.css)
- [interface/src/components/grid.js](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/grid.js)
- [interface/src/components/getRandomColor.js](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/getRandomColor.js)
