### ISSUE TITLE
Enable CORS (Cross-Origin Resource Sharing) for the api

### ISSUE THREAD

**Issue by im-prakher** [PecanProject/BETYdb-YABA#45]
The aim of this issue is to enable CORS (Cross-Origin Resource Sharing) for the application to allow resource sharing from other origins. Actually, the frontend application(currently under-development) needs to post data to the YABA app but it isn't allowed as of cross-origin policy, for which we need to enable CORS in the YABA app. 

It can be  done using Flask-CORS extension 
https://flask-cors.readthedocs.io/en/latest/

**Comment by dlebauer** [comment]
Implemented in PR #50 see https://github.com/PecanProject/BETYdb-YABA/blob/50088c7badbb66692ca19d4b4eb2ac6fb58479e5/client/client.py
