### ISSUE TITLE
Validate user-input API key

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#46]
After the API key is entered in the Welcome page, it should be validated (#18)

* [ ] check that API key is valid 
   * `select count(*) from users where apikey = $user_provided_apikey` should return `1`
* [ ] confirm that user name. Display the name returned by the following query:
   *  `select name from users where apikey = $user_provided_apikey

**Comment by im-prakher** [comment]
@dlebauer @KristinaRiemer While implementing the validation using the API key, I found that currently, the ` apikey` column for the `users` table for every row (user) is empty and null.

As by performing this query,
 `select count(*) from users where apikey = $user_provided_apikey` it will return `0`.

The app initializes the bety database from this URL, [`https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz`](https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz) , so, if you can update the users table here with `apikey`, this query might work.

For now, should  I perform validation based on the user's email in the database?.

**Comment by KristinaRiemer** [comment]
So you checked that all api keys are null with something like `select distinct(apikey) from users;`? 

I'm not really sure why the apikeys aren't showing up. When I log into my TERRA REF Bety account, I can see my own key under users. @dlebauer?

**Comment by dlebauer** [comment]
For the purposes of developing the functionality, feel free to use something like `update users set apikey = 'whatever_random_string' where user = 'myuser';`.

Instructions for generating api keys are here: https://pecan.gitbook.io/betydb-data-access/api-for-url-based-queries#for-administrators.  There is also a button in the interface where users can generate / recreate their own apikeys.

**Comment by im-prakher** [comment]
Done in #69
