### ISSUE TITLE
Set up development environment  

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#47]
Set up the environment for development using node js, create-react-app module.

This should be documented in README so that someone else can quickly get the application up and running

**Comment by im-prakher** [comment]
Done in -->
- [interface/package.json](https://github.com/PecanProject/BETYdb-YABA/blob/efb3b23d912241aab5d0d57f4237c7e3aa569104/interface/package.json)
- [interface/README.md](https://github.com/PecanProject/BETYdb-YABA/blob/efb3b23d912241aab5d0d57f4237c7e3aa569104/interface/README.md)
