### ISSUE TITLE
Set up github actions

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#48]
* [ ] super linter
* [ ] tests for python and js
* [ ] code coverage (eg codecov or sonarcube)
   * PR requires code coverage to stay the same or increase

**Comment by im-prakher** [comment]
We can use [super linter](https://github.com/github/super-linter) instead of pylint which can lint python as well as js and other languages code.

**Comment by im-prakher** [comment]
Done in #63
