### ISSUE TITLE
Write stylesheet for each endpoints' web page

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#49]
Write stylesheets for application endpoints to upload metadata

**Comment by im-prakher** [comment]
Done in
- [interface/src/components/stylesheets/style.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/style.css)
- [interface/src/components/stylesheets/navbar.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/navbar.css)
- [interface/src/components/stylesheets/homepage.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/homepage.css)
- [interface/src/components/stylesheets/upload1.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/upload1.css)
- [interface/src/components/stylesheets/upload2.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/upload2.css)
- [interface/src/components/stylesheets/visual.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/visual.css)
- [interface/src/components/stylesheets/shape-visual.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/shape-visual.css)
- [interface/src/components/stylesheets/leaflet.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/leaflet.css)
- [interface/src/components/stylesheets/footer.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/footer.css)
- [interface/src/components/stylesheets/error.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/error.css)
- [interface/src/components/stylesheets/success.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/success.css)
