### ISSUE TITLE
Describe data format requirements in README

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#54]
* Link to this template (if not already) https://docs.google.com/spreadsheets/d/1Fr_8xYOucyCQ9WH5_1bfPTMpm3IhKX5oqW4UOMvPoSY/edit#gid=0
* Also add tables to readme w/ information from README spreadsheet (you can use [markdown tables generator](https://www.tablesgenerator.com/markdown_tables))
* Need to add shapefile specs

**Comment by im-prakher** [comment]
@dlebauer  Can you add some more information about shapefile specs?

**Comment by im-prakher** [comment]
@dlebauer @KristinaRiemer Should we close this issue now?

**Comment by dlebauer** [comment]
yes this was fixed by #69
