### ISSUE TITLE
Visualize the polygons

### ISSUE THREAD

**Issue by im-prakher** [PecanProject/BETYdb-YABA#56]
Created a `shape-visual.js` and `gmap.js` component that uses `react-leaflet` to visualize the GeoJSON data.

- [interface/src/components/shape-visual.js](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/shape-visual.js)
- [interface/src/components/gmap.js](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/gmap.js)
- [interface/src/components/stylesheets/shape-visual.css](https://github.com/PecanProject/BETYdb-YABA/blob/c622e2a55f59a9774c37eae57fda12b0ebb585f7/interface/src/components/stylesheets/shape-visual.css)

**Comment by dlebauer** [comment]
we don't need to visualize the shapefiles directly, we want to visualize the data after it has been inserted into the database. For example, to look at the map of experiments we want to test that this is valid ....


```sql
select experiments.name, sitename, st_asgeojson(geometry) as polygon from sites 
    join experiments_sites on sites.id = experiments_sites.site_id 
   join experiments on experiments.id = experiments_sites.experiment_id 
   where ????<find the stuff that hasn't been committed e.g. sites.created_at = just now>;
```

similar w/ joins to treatments and cultivars

**Comment by im-prakher** [comment]
Done in #69
