### ISSUE TITLE
Remove responsive navbar ... 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#61]
This is not needed b/c 
1. people won't be using this on mobile. 
2. navbar not needed (this is a form / workflow UI not a navagable website)

> Why isn't this display style part of the "Link" element CSS? The bar may change its elements spacing when the user clicks it & it may be better to start out with correct spacing.

_Originally posted by @Chris-Schnaufer in https://github.com/PecanProject/BETYdb-YABA/pull/50#discussion_r447877833_

**Comment by im-prakher** [comment]
Done in #69
