### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by KristinaRiemer** [PecanProject/BETYdb-YABA#64]
This should go in 
* the YABA repo's README 
* [the BETYdb docs](https://pecanproject.github.io/bety-documentation/dataentry/entering-meta-data.html#betydb-yaba-and-python-client-library). 
* These docs should be referenced in the PEcAn API documentation

User content: 
- Link to interface
- Description/screenshots of data tables/shapefiles (see #54), point out example data

Developer content: 
- Endpoints
- How to deploy interface

**Comment by im-prakher** [comment]
Done in #69
