### ISSUE TITLE
Implement testing as a matrix 

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/BETYdb-YABA#67]
For GitHub actions, can you use a matrix for testing the app, interface, etc. folders? It's easier to maintain a single YAML file than multiples of the same with minor variations.

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

The idea was to see if matrix could be used to combine the two Python tests into one file. I feel that putting Python and Node tests into the same file defeats simplification. If putting the Python app-test and client-tests into the same file using matrix makes things less simple, then that shouldn't be done.

_Originally posted by @Chris-Schnaufer in https://github.com/PecanProject/BETYdb-YABA/pull/63#issuecomment-675030735_

**Comment by im-prakher** [comment]
Done in #63
