### ISSUE TITLE
Setting up the Tests and Documentation

### ISSUE THREAD

**Issue by saurabh1969** [PecanProject/BETYdb-YABA#7]
- Set up TravisCI
- Writing unit tests for YABA Flask api.
    - for sample data at each endpoint

Completion criteria:
- Commit with .travis.yml
- Sample data uploaded for testing
- also merge sample data and test data #11

**Comment by KristinaRiemer** [comment]
Travis has been implemented with yaml [here](https://github.com/saurabh1969/BETYdb-YABA/blob/master/.travis.yml) and tests are written [yaba_test.py](https://github.com/saurabh1969/BETYdb-YABA/blob/master/app/yaba_test.py). 

All that is left for @saurabh1969 is to add the Travis badge to the README to see if the build is passing or failing, and make sure the build passes once the second issue in #8 is resolved.

**Comment by saurabh1969** [comment]
All the test are passing in the latest commit of both PR. Build status tag is also attached to both the branch.Latest commit links-
[api-57c50d](https://github.com/saurabh1969/BETYdb-YABA/commit/57c50dfc9c28cacf28a709bf8af0e5e16444a1f3)

[client-f5e54](https://github.com/saurabh1969/BETYdb-YABA/commit/f5e54e38c81cfbea4c9f3a222c7ca8a6db2d0f38)
