### ISSUE TITLE
Fix metadata upload API

### ISSUE THREAD

**Issue by KristinaRiemer** [PecanProject/BETYdb-YABA#8]
There are currently two issues: 
1. In `credentials.yaml`, the `PGHOST` setting varies depending on the user's IP and breaks (at least on Macs) when set as `localhost`
2. The sites table endpoint is not working

@Chris-Schnaufer might be able to help @saurabh1969 troubleshoot #1?

**Comment by Chris-Schnaufer** [comment]
We need an update on this. Moving it to the next milestone

**Comment by saurabh1969** [comment]
sites table endpoint is implemented successfully .We can see in latest commit at #12 .We can close this issue.
