### ISSUE TITLE
Missing JsonSchema module

### ISSUE THREAD

**Issue by eshantri** [PecanProject/BETYdb-YABA#80]
![Screenshot from 2021-02-28 23-58-01](https://user-images.githubusercontent.com/48446729/109456708-6a6e9780-7a7f-11eb-893e-59a0e86689a2.png)

Upon running the yaba_api_1 container in my local machine I found that the following error pops up and causes the yaba_api_1 container to exit with code 1. The only fix that seems to work is by writing `jsonschema==3.2.0` in the app/requirements.txt file, though it gives the following warning-
![Screenshot from 2021-03-01 10-41-14](https://user-images.githubusercontent.com/48446729/109457173-54ada200-7a80-11eb-84d1-4eda7f3b106f.png)

**Comment by dlebauer** [comment]
@eshantri thank you for reporting this problem ... were you running this using docker or on your regular operating system?

**Comment by eshantri** [comment]
@dlebauer I was running this using docker,as per the steps mentioned in the documentation.

**Comment by eshantri** [comment]
#81 Fixes the error
