### ISSUE TITLE
Not able to find a sync_url in database - ERROR: 255

### ISSUE THREAD

**Issue by cryolune** [PecanProject/BETYdb-YABA#84]
While doing the setup of **BETYdb-YABA** app, I came across an issue when I entered the command `docker-compose run --rm bety sync` after following the documentation of this app.
**_" Did not find a sync_url in database, please update database, or provide script with DUMPURL.
ERROR: 255 "_**
<br></br>
![](https://i.ibb.co/zs1mx6p/Screenshot-from-2021-03-26-14-18-44.png)

**Comment by dlebauer** [comment]
Can you check if adding this line to the environment section of docker-compose.yml helps? https://github.com/terraref/brapi/blob/ac17464e003056394ddec7ba97f5a21e0d9dd968/docker-compose.yml#L38

**Comment by cryolune** [comment]
@dlebauer it worked, thanks 😀

**Comment by dlebauer** [comment]
Great - can you submit a PR for that? You can copy-paste the line here: https://github.com/terraref/brapi/edit/master/docker-compose.yml

**Comment by cryolune** [comment]
sure working on it.

**Comment by dlebauer** [comment]
fixed by https://github.com/PecanProject/BETYdb-YABA/issues/85
